# -*- coding: utf-8 -*-
"""guessthenumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jp0I0MTQoZpkwGZInNbVGNik84jempbU
"""

import random 
n= random.randint(0,9)

while(True):
    guess= int(input("enter guess: "))
    if (guess== n+1) or (guess==n-1) :
      print("very close")

    elif (guess== n+2) or (guess==n-2):
       print("close")
    elif (guess == n-3) or (guess== -4) or (guess==n+3) or (guess == n+4) :
       print("far")
    elif (guess == n) :
        print("you are correct")
        break
    elif(guess>9) or (guess<0):
      print("Please enter number between 0-9")
    else:
      print("Too Far")